# Generated by Django 5.0.2 on 2024-03-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktable',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
